kotlin.code.style=official
#Gradle
org.gradle.caching=true
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx3G"
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
#Kotlin Multiplatform
kotlin.mpp.enableCInteropCommonization=true
android.experimental.enableScreenshotTest=true
org.gradle.configuration-cache=true
kotlin.incremental.native=true