package io.github.kroune.nine_mens_morris_kmp_app.interactors

import io.github.kroune.nine_mens_morris_kmp_app.interactors.accountId.AccountIdInteractorI
import io.github.kroune.nine_mens_morris_kmp_app.interactors.accountId.AccountIdInteractorImpl
import io.github.kroune.nine_mens_morris_kmp_app.interactors.accountInfo.AccountInfoInteractorI
import io.github.kroune.nine_mens_morris_kmp_app.interactors.accountInfo.AccountInfoInteractorImpl
import io.github.kroune.nine_mens_morris_kmp_app.interactors.auth.AuthInteractorI
import io.github.kroune.nine_mens_morris_kmp_app.interactors.auth.AuthInteractorImpl
import io.github.kroune.nine_mens_morris_kmp_app.interactors.jwtToken.JwtTokenInteractorI
import io.github.kroune.nine_mens_morris_kmp_app.interactors.jwtToken.JwtTokenInteractorImpl
import io.github.kroune.nine_mens_morris_kmp_app.interactors.onlineGame.OnlineGameInteractorI
import io.github.kroune.nine_mens_morris_kmp_app.interactors.onlineGame.OnlineGameInteractorImpl
import io.github.kroune.nine_mens_morris_kmp_app.interactors.searchingForGame.SearchingForGameInteractorI
import io.github.kroune.nine_mens_morris_kmp_app.interactors.searchingForGame.SearchingForGameInteractorImpl

var jwtTokenInteractor: JwtTokenInteractorI = JwtTokenInteractorImpl()

var accountInfoInteractor: AccountInfoInteractorI = AccountInfoInteractorImpl()

var authRepositoryInteractor: AuthInteractorI = AuthInteractorImpl()

var accountIdInteractor: AccountIdInteractorI = AccountIdInteractorImpl()

var onlineGameInteractor: OnlineGameInteractorI = OnlineGameInteractorImpl()

var searchingForGameInteractor: SearchingForGameInteractorI = SearchingForGameInteractorImpl()