name: Test, build, deploy web artifacts to github pages

on:
  workflow_dispatch:
  release:

permissions:
  contents: write


env:
  repository_name: NineMensMorris

jobs:
  basicTest:
    runs-on: ubuntu-latest
    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache KMP tooling
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.konan
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            build
            composeApp/build
            composeApp/.gradle
            baselineprofile/build
          key: ${{ runner.os }}-unit-tests-${{ hashFiles('**/libs.versions.toml') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-unit-tests-${{ hashFiles('**/libs.versions.toml') }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run basic tests with Gradle
        run: ./gradlew testReleaseUnitTest --rerun

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.konan
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            build
            composeApp/build
            composeApp/.gradle
            baselineprofile/build
          key: ${{ runner.os }}-unit-tests-${{ hashFiles('**/libs.versions.toml') }}-${{ github.run_id }}

  uiTest:
    strategy:
      matrix:
        include:
          # android
          - target: allDevicesDebugAndroidTest --rerun -x test -x iosSimulatorArm64Test -x desktopTest -x wasmJsTest
            tag: android
            os: ubuntu-latest

          # ios
          - target: iosSimulatorArm64Test --rerun -x test -x connectedAndroidTest -x desktopTest -x wasmJsTest
            tag: ios
            os: macos-13

          #          # web
          #          - target: wasmJsBrowserTest --rerun -x test -x iosSimulatorArm64Test -x connectedAndroidTest -x desktopTest -x wasmJsTest
          #            tag: wasm
          #            os: ubuntu-latest

          # desktop
          - target: desktopTest --rerun -x test -x test -x iosSimulatorArm64Test -x connectedAndroidTest -x wasmJsTest
            tag: desktop
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache KMP tooling
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.konan
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            build
            composeApp/build
            composeApp/.gradle
            baselineprofile/build
          key: ${{ runner.os }}-ui-tests-${{ matrix.tag }}-${{ hashFiles('**/libs.versions.toml') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-ui-tests-${{ matrix.tag }}--${{ hashFiles('**/libs.versions.toml') }}

      - name: enable KVM
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew ${{ matrix.target }}

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.konan
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            build
            composeApp/build
            composeApp/.gradle
            baselineprofile/build
          key: ${{ runner.os }}-ui-tests-${{ matrix.tag }}-${{ hashFiles('**/libs.versions.toml') }}-${{ github.run_id }}

  produceArtifacts:
    needs: [ basicTest, uiTest ]
    strategy:
      matrix:
        include:
          # web
          - target: wasmJsBrowserDistribution
            tag: Web
            after: |
            directory: composeApp/build/dist/wasmJs/productionExecutable/
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache KMP tooling
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.konan
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            build
            composeApp/build
            composeApp/.gradle
            baselineprofile/build
          key: ${{ runner.os }}-produce-artifacts-${{ matrix.tag }}-${{ hashFiles('**/libs.versions.toml') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-produce-artifacts-${{ matrix.tag }}-${{ hashFiles('**/libs.versions.toml') }}

      - name: enable KVM
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Produce artifacts
        run: ./gradlew ${{ matrix.target }} -x test -x iosSimulatorArm64Test -x connectedAndroidTest -x desktopTest -x wasmJsTest

      - name: Execute after actions
        run: ${{ matrix.after }}

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.konan
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            build
            composeApp/build
            composeApp/.gradle
            baselineprofile/build
          key: ${{ runner.os }}-produce-artifacts-${{ matrix.tag }}-${{ hashFiles('**/libs.versions.toml') }}-${{ github.run_id }}

      - name: Upload artifacts to github
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }}-${{ matrix.tag }}-artifact
          path: ${{ matrix.directory }}

  uploadWebArtifactsToGithubPages:
    needs: [ produceArtifacts ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ../artifacts
      - uses: actions/checkout@v4
        with:
          repository: 'kroune/kroune.github.io'
      - name: Upload artifacts to artifacts github pages
        env:
          GH_TOKEN: ${{ secrets.WEB_ARTIFACTS_GITHUB_TOKEN }}
        run: |
          mv LICENSE ../
          rm -rf *
          cp -r ../artifacts/NineMensMorris-Web-artifact/* .
          mv ../LICENSE .
          ls -hlas
          git config user.name "GitHub Actions Bot"
          git config user.email "123553746+kroune@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit . -m "update web artifacts"
          git push
#
#  uploadArtifactsToMicroservice:
#    needs: [ produceArtifacts ]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download all artifacts
#        uses: actions/download-artifact@v4
#      - name: Upload artifacts to artifacts microservice
#        run: |
#          ls -hlas
#          for FILE in *; do
#            PLATFORM_NAME=$(echo $FILE | cut -d "-" -f 2)
#            echo "Compressing file for $PLATFORM_NAME, file - $FILE"
#            7z a -mx=9 ../$FILE.7z $FILE
#            curl -v --connect-timeout 30 -m 300 -X POST -T ../$FILE.7z https://nine-men-s-morris.me/artifacts-service/upload?auth_token=${{ secrets.AUTH_TOKEN }}\&type=Testing\&platform=$PLATFORM_NAME\&commit=${{ github.event.head_commit.id }}\&branch=${{ github.ref_name }}
#          done
