name: Builds app on all targets

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          # android
          - target: assembleRelease
            tag: android
            directory: composeApp/build/outputs/apk/release/composeApp-release.apk
            os: ubuntu-latest
          # macos
          - target: packageReleasePkg
            tag: ios
            directory: composeApp/build/compose/binaries/main-release/pkg/
            os: macos-latest
          # ios
          - target: iosSimulatorArm64Binaries
            tag: ios
            directory: composeApp/build/libs/composeApp-desktop.jar
            os: macos-latest
          # web
          - target: wasmJsBrowserDistribution
            tag: web
            directory: composeApp/build/dist/wasmJs/productionExecutable/
            os: ubuntu-latest
          # linux
          - target: packageReleaseDeb
            tag: linux
            directory: composeApp/build/compose/binaries/main-release/deb/
            os: ubuntu-latest
          # windows
          - target: packageReleaseExe
            tag: windows
            directory: composeApp/build/compose/binaries/main-release/exe/
            os: windows-latest
    runs-on: ${{ matrix.os }}

    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      repository_name: NineMensMorris
    steps:
    - uses: actions/checkout@v4
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v4
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'zulu'
    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: ${{ matrix.target }}
    - name: Upload artifacts - ${{ env.repository_name }}
      uses: actions/upload-artifact@v4
      with:
        name:  ${{ env.repository_name }}-${{ matrix.tag }}-artifact
        path: ${{ matrix.directory }}
    - name: List all directories
      run: find composeApp/build/