on:
  workflow_dispatch:

jobs:
  producePlots:
    runs-on: ubuntu-latest
    steps:
      - name: Plot artifacts size
        uses: kroune/artifacts-size-plot@v0.0.1
        with:
          github-token: ${{ secrets.IMG_REPO_GITHUB_TOKEN }}
          repository-owner: "kroune"
          repository-name: "nine-mens-morris-app-kmp"

      - uses: actions/checkout@v4
        with:
          repository: 'kroune/kroune-img-hosting'
      - name: Upload artifacts to artifacts github images repository
        env:
          GH_TOKEN: ${{ secrets.IMG_REPO_GITHUB_TOKEN }}
        run: |
          cp -rf ~/plot-artifacts .
          ls -hlas
          git config user.name "GitHub Actions Bot"
          git config user.email "123553746+kroune@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit . -m "update imgs"
          git push